# Generated by Django 4.0.3 on 2022-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='account_emailaddress',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
